name: Tests

on: [pull_request, push, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Check build, markup, and links
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3"
      - name: Install uv
        uses: hynek/setup-cached-uv@v2
      - name: Build docs
        run: make html
      - name: Link check
        run: make linkcheck
        continue-on-error: true
